#!/bin/bash

# DO NOT SOURCE THIS SCRIPT. Source nvs.sh instead.

# This script enables running NVS as an executable.  The one limitation is
# that it cannot modify environment variables (PATH) of the calling shell,
# therefore the 'nvs use' command is not available.

export NVS_EXECUTE=1
source ./nvs.sh
nvs $*
